Milestone 3
joshualyngdoh/To-do-list pull request #3
Opened 2023-01-19 10:32 UTC by joshualyngdoh

# Description
- Page is now Interactive
- Updated README
- Check for linter errors

2023-01-19 14:27 UTC, youmari requested changes
Hi @joshualyngdoh , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great commit messages
✔️ PRO PR
✔️ No linter error 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 14:27 UTC, youmari commented on src/Status.js
> +}
- [x] when make the tasks status: true and reload the page twice they become `status: false` again please make sure to fix that you can see the bug in the following  video : 
https://www.loom.com/share/f545a61f729145e398400d6314ce58c6

2023-01-19 15:27 UTC, joshualyngdoh commented on src/Status.js
> +}
Thank you for your feedback

2023-01-20 09:34 UTC, mikethreels approved these changes
Hi Josh, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- linters are passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 09:37 UTC, joshualyngdoh commented
Thank you

2023-01-20 09:37 UTC, merged